import {
  AppWindow,
  BadgeCheck,
  BarChart3,
  Briefcase,
  Building2,
  CalendarClock,
  CheckCircle2,
  Compass,
  FileText,
  Globe,
  GraduationCap,
  Handshake,
  Headset,
  Image as ImageIcon,
  Layers,
  Lightbulb,
  LineChart,
  Megaphone,
  MonitorSmartphone,
  Palette,
  Printer,
  Rocket,
  Search,
  Settings2,
  ShieldCheck,
  ShoppingCart,
  Sparkles,
  Target,
  TrendingUp,
  UserCheck,
  Users,
  UsersRound,
  Wrench,
  type LucideIcon,
} from 'lucide-react';

const ICONS: Record<string, LucideIcon> = {
  AppWindow,
  BadgeCheck,
  BarChart3,
  Briefcase,
  Building2,
  CalendarClock,
  CheckCircle2,
  Compass,
  FileText,
  Globe,
  GraduationCap,
  Handshake,
  Headset,
  Image: ImageIcon,
  Layers,
  Lightbulb,
  LineChart,
  Megaphone,
  MonitorSmartphone,
  Palette,
  Printer,
  Rocket,
  Search,
  Settings2,
  ShieldCheck,
  ShoppingCart,
  Sparkles,
  Target,
  TrendingUp,
  UserCheck,
  Users,
  UsersRound,
  Wrench,
};

export const ICON_NAMES = Object.keys(ICONS).sort();

export function Icon({ name, className, size = 22 }: { name?: string; className?: string; size?: number }) {
  const Cmp = (name && ICONS[name]) || Sparkles;
  return <Cmp className={className} size={size} strokeWidth={1.75} aria-hidden />;
}
